FROM node:24-alpine AS build

WORKDIR /app

RUN corepack enable

COPY package.json ./
COPY . ./

RUN pnpm install --no-frozen-lockfile && pnpm build

FROM nginx:1.29.8-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]